### PR TITLE
[DRFT-150] Change comparison 'Clear filters' to 'Reset filters'

### PR DESCRIPTION
**Pull request by johnsonm325**
To reproduce:
Create a comparison
Modify any or all filters (fact and state filters)
Click 'Clear filters'

All filters will be removed.
This PR changes the text to 'Reset filters' and when the above steps are reproduced, the filters will return to their original state.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by johnsonm325** [comment]
@vkrizan Not sure why this is failing. I did an npm update on a previous merge and then rebased this branch. Then I ran `rm -rf node_modules/` and `npm i`. npm version is 7.19.1

**Comment by vkrizan** [comment]
@johnsonm325 The failure might be because of the incompatibility with NPM6, which this repo uses.
```
$ npm --version
6.14.12
```

If this does not need any new packages, then I'd suggest to take out the package-lock change out.

**Comment by johnsonm325** [comment]
@vkrizan Fixed!

**Review by vkrizan — APPROVED** [review]
Works well.

@johnsonm325 would there be a PR for other tables/filters as per task?

**Comment by vkrizan** [comment]
While trying this out, I've noticed some weird responsiveness behavior.
Notice how the filter input is too wide when the default filters are applied and pushes the pagination to next line:
Screenshot 2021-07-20 at 11-10-54 Comparison - Drift Red Hat Insights
vs
Screenshot 2021-07-20 at 11-11-49 Comparison - Drift Red Hat Insights

**Pull request merged**
