### PR TITLE
(DRFT-40) Marks obfuscated values with icon

### PR DESCRIPTION
**Pull request by petrblaho**

### CODE REVIEW

**Comment by petrblaho** [comment]
This is just grey background, padlock icon still missing...

**Comment by petrblaho** [comment]
https://issues.redhat.com/browse/DRFT-40

**Comment by petrblaho** [comment]
Updated with lock icon

**Comment by petrblaho** [comment]
Updated colors as per what Katie confirmed.

**Comment by sthirugn** [comment]
@johnsonm325 can you please review when you get a chance

**Review by johnsonm325 — APPROVED** [review]
Looks great!

**Pull request merged**
