### PR TITLE
Fire proper clear all filters event on modal load

### PR DESCRIPTION
**Pull request by karelhala**
When systems modal is opened inventory event `CLEAR_ALL` is fired, this causes inventory to incorrectly load systems as it ignores `source=insights` if filters are cleared. This PR adds new event that clear all filters from drift perspective, meaning it will set `activeFilters` to undefined so inventory will respect default filters and shows correct systems. This event is fired only on modal render so if user clears filters in modal proper systems are shown and when some filter is applied and modal is closed and re-opened this modal shows again systems for default filter.

### CODE REVIEW

**Comment by karelhala** [comment]
ping @johnsonm325

**Comment by johnsonm325** [comment]
@karelhala You'll have to help me understand how to test this. I must be doing something wrong or missing the point because I'm not seeing a difference.

**Comment by karelhala** [comment]
@johnsonm325 well if you open network tab in development console and open systems modal you can see that without this change fetching hosts has no `source` filter defined, with this patch it will respect this filter and prefilter the systems based on correct source that is also visible in filters.

**Comment by johnsonm325** [comment]
Here's the request URL on master: `https://ci.foo.redhat.com:1337/api/inventory/v1/hosts?per_page=50&page=1&order_by=updated&order_how=DESC&staleness=fresh&staleness=stale&&registered_with=insights`
Here's the request URL on this PR: `https://ci.foo.redhat.com:1337/api/inventory/v1/hosts?per_page=50&page=1&order_by=updated&order_how=DESC&staleness=fresh&staleness=stale&&registered_with=insights`

Is this what you're referring to?

**Comment by karelhala** [comment]
Running correct travis

**Review by johnsonm325 — APPROVED** [review]

**Comment by sthirugn** [comment]
@karelhala when do you want this in prod?

**Pull request merged**
