### PR TITLE
Enable global filter SID and SAP flag

### PR DESCRIPTION
**Pull request by karelhala**
### Fully integrate drift to global filter

As we approach further the monday global filter release we have to consume SID and workloads values from global filter. Also start using new version of chrome global filter mapper.

### CODE REVIEW

**Comment by karelhala** [comment]
ping @johnsonm325

**Comment by karelhala** [comment]
Running correct travis

**Review by johnsonm325 — APPROVED** [review]

**Comment by sthirugn** [comment]
@karelhala when do you want this in prod?

**Comment by karelhala** [comment]
@sthirugn next monday we will be releasing all other apps but since drift is partially integrated we can release anytime you feel good about it.

**Comment by johnsonm325** [comment]
@karelhala Needs rebase

**Pull request merged**
