### PR TITLE
Add pagination to bottom of table also

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by beav** [comment]
I still only see the pagination at the top with this patch. Do I need to do anything special after applying?

**Comment by ehelms** [comment]
@beav Can you paste a screenshot ?

**Comment by johnsonm325** [comment]
@ehelms I can see it on the top and the bottom. But the new pagination at the bottom is visible on empty state and loading.

**Comment by beav** [comment]
> @beav Can you paste a screenshot ?

It's there now for me :man_shrugging: I guess something was cached

**Pull request merged**
