### PR TITLE
[DRFT-313] Get diff of current and systems to add in notifications

### PR DESCRIPTION
**Pull request by johnsonm325**
open a baseline, system notifications tab
make sure there is at least one system present (system_A)
open Add system
make sure that system_A is visible on the page (with the greyed-out checkmark)
select all via Bulk selector

Clicking Submit does nothing and creates 500 error. This is because bulk select adds all of the systems on the page to the array of systems that are attempted to be added to the baseline notification DB. Because one of those ids is already associated, it fails with a 500. This PR finds the diff of the systems to be added and the existing systems so that a duplicate id isn't requested.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by sthirugn** [comment]
I still see 500 when I do the following scenario:
1. I add a new system, submit it.
2. Edit again, without changing anything 

If I do a page refresh between steps 1 and 2, I don't see 500

**Comment by petrblaho** [comment]
Works for me... @sthirugn I am curious what we do differently :-)

**Comment by johnsonm325** [comment]
@sthirugn I was able to repro. Try my new fix.

**Comment by sthirugn** [comment]
I don't see the 500 error any more.

**Review by sthirugn — APPROVED** [review]

**Pull request merged**
