### PR TITLE
[DRFT-367] Update wording for notifications

### PR DESCRIPTION
**Pull request by jpramos123**
Made the changes on naming inconsistencies in single baseline tab.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

### CODE REVIEW

**Comment by johnsonm325** [comment]
The kebab here should read `Delete associated system`
image

The delete modal should read like so, if you have selected multiple associated systems to be deleted:
```
Delete associated systems
You have selected multiple associated systems to be deleted.
Deleting an associated system cannot be undone.
```
image

The delete modal should read like so if you have selected only one associated system to be deleted:
```
Delete associated system
You have selected an associated system to be deleted.
Deleting an associated system cannot be undone.
```
image

**Comment by jpramos123** [comment]
@johnsonm325 Thanks for your review

I have made the changes

Thanks

**Comment by johnsonm325** [comment]
@jpramos123 Still need to change the title of the modal here to read `Delete associated system`.
image

And you'll need to change the modal for deleting multiple system associations as well.

**Review by johnsonm325 — APPROVED** [review]
lgtm

Great job

**Pull request merged**
