### PR TITLE
Add error output validation for edit baseline name and facts

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This shouldn't disable category on 'Add Fact'

**Comment by ehelms** [comment]
I have made a decent round of updates to this to more accurately send patch requests and get results for add vs. edit states. If you try to 'Add fact' a fact with an existing name and value, you should now see the server report a 500 error. This shows the validation in action but is obviously a backend bug.

**Comment by johnsonm325** [comment]
I'm getting the error message on both the name box and value box. Is that expected?
image
Then, when I tried to change the name right there in the box, I get the following error:
image

**Comment by johnsonm325** [comment]
Another bug I found. If you try to edit a category, the "This is a category" box is not disabled. We want it so once you've created a category and then try to edit it, you can't switch that on/off again.

**Comment by beav** [comment]
:heart:

**Pull request merged**
