### PR TITLE
[DRFT-366] Disable Apply Changes button when no change made in basket

### PR DESCRIPTION
**Pull request by johnsonm325**
When no changes have been made to the selected basket, the apply changes button should be disabled.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

### CODE REVIEW

**Review by jpramos123 — APPROVED** [review]
LGTM!

**Review by jpramos123 — CHANGES_REQUESTED** [review]
Just need to resolve the conflict :)

**Comment by johnsonm325** [comment]
@jpramos123 merging other PR fixed this conflict. Can I get your approval again?

**Review by jpramos123 — APPROVED** [review]
LGTM!

**Pull request merged**
