### PR TITLE
Add loading table skeleton

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This is updated to be rebased on the empty state. I've taken the original design and re-worked it to match other render functionality we had already and how I'd approached the loading. Let me know what you think about this overall @johnsonm325

**Comment by johnsonm325** [comment]
Do we want to include the "Add System" button in the loading screen?

image

**Comment by ehelms** [comment]
Hrmm, fair thought. I will see what it takes to pull that off.

**Comment by ehelms** [comment]
Updated to fix a bug and set the button to loading as well.

**Pull request merged**
