### PR TITLE
Highlight different rows

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by beav** [comment]
@ehelms rebase plz

**Comment by beav** [comment]
@ehelms can you make the highlight go all the way across to include the state + name?

**Comment by ehelms** [comment]
The mock ups do not have it extended across the entire row. We can discuss
with Rox.

**Comment by beav** [comment]
if it's the same as the mockup, that is good enough for me. We can discuss during next UX meeting.

**Pull request merged**
